services:
  postgres:
    image: 'postgres:17'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'

  spring-boot-url-shortener:
    image: url-shortner:0.0.1-SNAPSHOT   # <- match your built image name
    container_name: spring-boot-url-shortener
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - postgres
